Controllers/MeterController.cs
using EBS.viewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace EBS.Controllers
{
    [Authorize]
    public class MeterController : Controller
    {
        // Instance of the connection String
        private readonly string SecConn = ConfigurationManager.ConnectionStrings["SecConn"].ConnectionString;

        // GET: Meter
        public ActionResult Index()
        {
            MeterWrapper wrapper = new MeterWrapper();
            wrapper.meterList = GetMeters();
            return View(wrapper);
        }

        // POST: /Meter/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(MeterWrapper model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        InsertMeter(model);
        //        return RedirectToAction("Index");
        //    }
        //    return View(model);
        //}

        // POST: Get Meter Data
        public JsonResult GetMeterData(int id)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {

                connection.Open();
                string query = "SELECT * FROM Meters WHERE MeterID = @MeterID";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@MeterID", id);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            // Populate the meter object
                            MeterWrapper meter = new MeterWrapper
                            {
                                MeterID = Convert.ToInt32(reader["MeterID"]),
                                cID = Convert.ToInt32(reader["cID"]),
                                lockNumber = Convert.ToInt32(reader["lockNumber"]),
                                Type = reader["Type"].ToString(),
                                Status = reader["Status"].ToString()
                            };

                            // Return the meter Data as JSON
                            return Json(meter, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
            }

            // If no data found, return an empty JSON object
            return Json(new MeterWrapper(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateMeter(MeterWrapper model)
        {
            if (ModelState.IsValid)
            {
                UpdateMeterMethod(model);
                return Json(new { success = true, message = "Meter Updated Successfully!" });
            }
            return Json(new { success = false, message = "Meter Update Failed!" });
        }

        // POST: Delete
        [HttpPost]
        public JsonResult Delete(int id)
        {
            DeleteMeter(id);
            return Json(new { success = true, message = "Meter Deleted Successfully!" });
        }

        // GET: /Meter/BulkInsert
        //[HttpGet]
        //public ActionResult BulkInsert()
        //{
        //    return View();
        //}

        //// POST: /Meter/BulkInsert
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult BulkInsert(List<MeterWrapper> model)
        //{
        //    try
        //    {
        //        using (SqlConnection connection = new SqlConnection(SecConn))
        //        {
        //            connection.Open();

        //            // Start a SQL transaction
        //            using (SqlTransaction transaction = connection.BeginTransaction())
        //            {
        //                try
        //                {
        //                    // Create a SQL command for bulk insert within the transaction
        //                    using (SqlCommand command = connection.CreateCommand())
        //                    {
        //                        command.Transaction = transaction;
        //                        command.CommandText = "INSERT INTO Meters (SerialNumber, Type, Status) VALUES (@SerialNumber, @Type, @Status)";

        //                        foreach (var wrapper in model)
        //                        {
        //                            // Set parameter values for each Meter
        //                            command.Parameters.AddWithValue("@SerialNumber", wrapper.SerialNumber);
        //                            command.Parameters.AddWithValue("@Type", wrapper.Type);
        //                            command.Parameters.AddWithValue("@Status", wrapper.Status);

        //                            // Execute the command for each Meter
        //                            command.ExecuteNonQuery();

        //                            // Clear parameters for the next iteration
        //                            command.Parameters.Clear();
        //                        }
        //                    }

        //                    // Commit the transaction if everything is successful
        //                    transaction.Commit();
        //                }
        //                catch (Exception ex)
        //                {
        //                    // Roll back the transaction if an error occurs
        //                    transaction.Rollback();
        //                    ModelState.AddModelError("", "An Error Occured While Inserting Records, Please Try Again!" + ex.Message);

        //                }
        //            }
        //        }

        //        return RedirectToAction("Index"); // Redirect to a success page
        //    }
        //    catch (Exception ex)
        //    {
        //        // Handle the exception and provide appropriate error feedback to the user
        //        ModelState.AddModelError("", "An error occurred while inserting data: " + ex.Message);
        //        return View(model); // Show the input form with error messages
        //    }
        //}



        // Fetching Meter Information From the Database
       
        private List<MeterVM> GetMeters()
        {
            List<MeterVM> meters = new List<MeterVM>();

            using (SqlConnection Connection = new SqlConnection(SecConn))
            {
                Connection.Open();
                string query = "SELECT * FROM Meters";
                using (SqlCommand command = new SqlCommand(query, Connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            meters.Add(new MeterVM
                            {
                                MeterID = Convert.ToInt32(reader["MeterID"]),
                                cID = Convert.ToInt32(reader["cID"]),
                                lockNumber = Convert.ToInt32(reader["lockNumber"]),
                                Type = reader["Type"].ToString(),
                                Status = reader["Status"].ToString()

                            });
                        }
                    }
                }
            }

            return meters;
        }


        // Insert Meter Data
        private void InsertMeter(MeterWrapper model)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string Insertquery = "INSERT INTO Meters (cID, lockNumber, Type, Status) VALUES (@cID, @lockNumber, @Type, @Status)";

                using (SqlCommand command = new SqlCommand(Insertquery, connection))
                {
                    command.Parameters.AddWithValue("@lockNumber", model.lockNumber);
                    command.Parameters.AddWithValue("@Type", model.Type);
                    command.Parameters.AddWithValue("@Status", model.Status);

                    command.ExecuteNonQuery();
                }
            }
        }

        // Update Meter Info
        private void UpdateMeterMethod(MeterWrapper model)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string query = "UPDATE Meters SET cID = @cID lockNumber = @lockNumber, Type = @Type, Status = @Status WHERE MeterID = @MeterID";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@MeterID", model.MeterID);
                    command.Parameters.AddWithValue("@cID", model.cID);
                    command.Parameters.AddWithValue("@lockNumber", model.lockNumber);
                    command.Parameters.AddWithValue("@Type", model.Type);
                    command.Parameters.AddWithValue("@Status", model.Status);

                    command.ExecuteNonQuery();
                };
            }
        }

        // Delete Meter
        private void DeleteMeter(int id)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string DeleteQuery = "DELETE FROM Meters WHERE MeterID = @MeterID";

                using (SqlCommand command = new SqlCommand(DeleteQuery, connection))
                {
                    command.Parameters.AddWithValue("MeterID", id);
                    command.ExecuteNonQuery();
                }
            }
        }

    }
}

Views/Meter/BulkInsert.cshtml
@model List<EBS.viewModels.MeterWrapper>

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<style>
    .content {
        display: flex;
        justify-content: center;
        padding: 20px; /* Add padding around the table */
    }

    .table-container {
        max-width: 700px; /* Set a maximum width for the table container */
        width: 10%;
        padding-top: 20px;
    }

    .table thead th {
        white-space: nowrap; /* Prevent text wrapping */
    }

    .container {
        margin-left: 300px;
        padding-top: 30px;
        padding-left: 35px;
        padding-bottom: 20px;
    }
</style>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Create Meters | SEC</title>
</head>
<body>

    <div id="container">

        <h2><strong>Insert Meters</strong></h2>
        <br />

        @using (Html.BeginForm("BulkInsert", "Meter", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Serial Number</th>
                        <th>Type</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < 5; i++)
                    {
                        <tr>
                            <td>
                                @Html.LabelFor(m => Model[i].SerialNumber)
                                @Html.EditorFor(model => Model[i].SerialNumber, new { htmlAttributes = new { @class = "form-control form-control-lg form-control-serial" } })
                                @Html.ValidationMessageFor(m => Model[i].SerialNumber, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.LabelFor(m => Model[i].Type)
                                @Html.EditorFor(model => Model[i].Type, new { htmlAttributes = new { @class = "form-control form-control-lg form-control-type" } })
                                @Html.ValidationMessageFor(m => Model[i].Type, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.LabelFor(m => Model[i].Status)
                                @Html.EditorFor(model => Model[i].Status, new { htmlAttributes = new { @class = "form-control form-control-lg form-control-status" } })
                                @Html.ValidationMessageFor(m => Model[i].Status, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <br />
            <br />

            <div class="col-md-6 mb-4 pb-2" style="display: flex; justify-content: center; align-items: center;">
                <button type="submit" value="Create" class="btn btn-success btn-lg btn-block">Insert</button>
            </div>
        }

    </div>

    <div class="modal fade" id="validationModal" tabindex="-1" role="dialog" aria-labelledby="validationModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="validationModalLabel">Validation Error</h5>
                 
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Please enter valid data.
                </div>
             
            </div>
        </div>
    </div>


</body>
</html>

<!--Form Fields Validation Script-->
<script>
    // Function to hide the modal
    function hideValidationModal() {
        $('#validationModal').modal('hide');
    }

    // Text Input Validation
    function validateText(input) {
        if (!isNaN(Number(input.value))) {
            // Show a Bootstrap modal with the validation message
            $('#validationModal').modal('show');
            input.value = '';
        }
    }

    // Number validation function
    function validateNumber(input) {
        if (isNaN(Number(input.value))) {
            // Show a Bootstrap modal with the validation message
            $('#validationModal').modal('show');
            input.value = '';
        }
    }

    // Attach listeners to input fields by class when they lose focus (blur)
    const serialInputs = document.querySelectorAll('.form-control-serial');
    const typeInputs = document.querySelectorAll('.form-control-type');
    const statusInputs = document.querySelectorAll('.form-control-status');

    serialInputs.forEach(input => {
        input.addEventListener('blur', () => {
            validateNumber(input);
        });
    });

    typeInputs.forEach(input => {
        input.addEventListener('blur', () => {
            validateText(input);
        });
    });

    statusInputs.forEach(input => {
        input.addEventListener('blur', () => {
            validateText(input);
        });
    });

    // Attach click event listener to the "OK" button in the modal
    document.getElementById('modalOkButton').addEventListener('click', hideValidationModal);
</script>

Views/Meter/Create.cshtml
@model EBS.viewModels.MeterVM

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Meter | SEC</title>
    <link href="~/Content/Registeration.css" rel="stylesheet" />

</head>
<body>

    @using (Html.BeginForm("Create", "Meter", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <section class="vh-100 gradient-custom;" ; style="font-family: Verdana, Geneva, Tahoma, sans-serif; ">
            <div class="container py-5 h-100">
                <div class="row justify-content-center align-items-center h-100">

                    <div class="col-12 col-lg-9 col-xl-7">
                        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">

                            <div class="card-body p-4 p-md-5">
                                <h2 class="mb-4 pb-2 pb-md-0 mb-md-5"><strong>Create Meter</strong></h2>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="row">
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(m => m.SerialNumber)
                                            @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "serialN" } })
                                            @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Type)
                                            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "type" } })
                                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>

                                <div class="row">
                                
                                    <div class="col-md-12 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Status)
                                            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "status" } })
                                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>

                                <div class="row">
                                        <div class="col-md-6 mb-4 pb-2">
                                            <input type="submit" value="Create" class="btn btn-success btn-lg btn-block" />

                                        </div>


                                        <div class="col-md-6 mb-4 pb-2">
                                            @Html.ActionLink("Back", "Index", "Meter", null, new { @class = "btn btn-secondary btn-lg btn-block" })
                                        </div>

                                </div>


                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!--The script below performs dynamic calculation to produce the product and sub of the current reading, previous reading, usage and rate-->

            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


            <script>

                // Text Input Validation
                function validateText(input) {
                    if (!isNaN(Number(input.value))) {
                        alert('Please enter text');
                        input.value = '';
                    }
                }

                // Number validation function
                function validateNumber(input) {
                if (isNaN(Number(input.value))) {
                    alert('Please enter a number');
                input.value = '';
                }
            }

                // Get elements
                const serialN = document.querySelector('#serialN');
                const type = document.querySelector('#type');
                const iDate = document.querySelector('#iDate');
                const statuss = document.querySelector('#status');

            // Attach listeners


                serialN.addEventListener('input', () => {
                    validateNumber(serialN);
            });

                type.addEventListener('input', () => {
                    validateText(type);
            });

                statuss.addEventListener('input', () => {
                    validateText(statuss);
            });


          
            </script>

        </section>
        

    }
</body>
</html>

Views/Meter/Delete.cshtml
@model EBS.viewModels.MeterVM

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete Meter | SEC</title>
    <link href="~/Content/Registeration.css" rel="stylesheet" />

</head>
<body>

    @using (Html.BeginForm("Delete", "Meter", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <section class="vh-100 gradient-custom;" ; style="font-family: Verdana, Geneva, Tahoma, sans-serif; ">
            <div class="container py-5 h-100">
                <div class="row justify-content-center align-items-center h-100">

                    <div class="col-12 col-lg-9 col-xl-7">
                        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">

                            <div class="card-body p-4 p-md-5">
                                <h2 class="mb-4 pb-2 pb-md-0 mb-md-5"><strong>Update Meter</strong></h2>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.MeterID)

                                <div class="row">
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(m => m.SerialNumber)
                                            @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "serialN", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Type)
                                            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "type", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>

                                <div class="row">



                                    <div class="col-md-12 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Status)
                                            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "status", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 mb-4 pb-2">
                                        <button type="submit" value="Create" class="btn btn-danger btn-lg btn-block">Delete</button>
                                    </div>


                                    <div class="col-md-6 mb-4 pb-2">
                                        @Html.ActionLink("Back", "Index", "Meter", null, new { @class = "btn btn-secondary btn-lg btn-block" })
                                    </div>

                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>


           

        </section>


    }
</body>
</html>

Views/Meter/Edit.cshtml
@model EBS.viewModels.MeterVM

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update Meter | SEC</title>
    <link href="~/Content/Registeration.css" rel="stylesheet" />

</head>
<body>

    @using (Html.BeginForm("Edit", "Meter", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <section class="vh-100 gradient-custom;" ; style="font-family: Verdana, Geneva, Tahoma, sans-serif; ">
            <div class="container py-5 h-100">
                <div class="row justify-content-center align-items-center h-100">

                    <div class="col-12 col-lg-9 col-xl-7">
                        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">

                            <div class="card-body p-4 p-md-5">
                                <h2 class="mb-4 pb-2 pb-md-0 mb-md-5"><strong>Update Meter</strong></h2>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.MeterID)

                                <div class="row">
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(m => m.SerialNumber)
                                            @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "serialN" } })
                                            @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Type)
                                            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "type" } })
                                            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>

                                <div class="row">
                                   

                                 
                                    <div class="col-md-12 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Status)
                                            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control form-control-lg", id = "status" } })
                                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 mb-4 pb-2">
                                        <button type="submit" value="Create" class="btn btn-primary btn-lg btn-block">Update</button>
                                    </div>


                                    <div class="col-md-6 mb-4 pb-2">
                                        @Html.ActionLink("Back", "Index", "Meter", null, new { @class = "btn btn-secondary btn-lg btn-block" })
                                    </div>

                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!--The script below performs dynamic calculation to produce the product and sub of the current reading, previous reading, usage and rate-->

            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


            <script>

                // Text Input Validation
                function validateText(input) {
                    if (!isNaN(Number(input.value))) {
                        alert('Please enter text');
                        input.value = '';
                    }
                }

                // Number validation function
                function validateNumber(input) {
                if (isNaN(Number(input.value))) {
                    alert('Please enter a number');
                input.value = '';
                }
            }

                // Get elements
                const serialN = document.querySelector('#serialN');
                const type = document.querySelector('#type');
                const iDate = document.querySelector('#iDate');
                const statuss = document.querySelector('#status');

            // Attach listeners


                serialN.addEventListener('input', () => {
                    validateNumber(serialN);
            });

                type.addEventListener('input', () => {
                    validateText(type);
            });

                statuss.addEventListener('input', () => {
                    validateText(statuss);
            });



            </script>

        </section>


    }
</body>
</html>