Controllers/RatesController.cs
using EBS.viewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace EBS.Controllers
{
    [Authorize]
    public class RatesController : Controller
    {
        // Instance of the connection String
        private readonly string SecConn = ConfigurationManager.ConnectionStrings["SecConn"].ConnectionString;

        // GET: Rates
        public ActionResult Index()
        {
            rateWrapper wrapper = new rateWrapper();
            wrapper.rateList = GetAllRates();
            return View(wrapper);
        }

        // GET: /Rates/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Rates/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(rateWrapper model)
        {
            if (ModelState.IsValid)
            {
                InsertTarrif(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET Rate
        [HttpPost]
        public JsonResult GetRate(int id)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {

                connection.Open();
                string query = "SELECT * FROM Rates WHERE Id = @Id";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            // Populate the invoice object
                            rateWrapper rate = new rateWrapper
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                UsageLevelName = reader["UsageLevelName"].ToString(),
                                UsageLevelNumberStarts = Convert.ToInt32(reader["UsageLevelNumberStarts"]),
                                UsageLevelNumberEnds = Convert.ToInt32(reader["UsageLevelNumberEnds"]),
                                Rate = Convert.ToDecimal(reader["Rate"])
                            };

                            // Return the Invoice Data as JSON
                            return Json(rate, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
            }

            // If no data found, return an empty JSON object
            return Json(new rateWrapper(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateRate(rateWrapper model)
        {
            if (ModelState.IsValid)
            {
                UpdateTarrif(model);
                return Json(new { success = true, message = "Rate Update Successfully!" });
            }
            return Json(new { success = false, message = "Rate Update Failed. Please Try Again!" });
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            DeleteTarrif(id);
            return Json(new { success = true, message = "Rate Deleted Successfully!" });
        }

        // Fetching Rate Information From the Database
        private List<RateVM> GetAllRates()
        {
            List<RateVM> rates = new List<RateVM>();

            using (SqlConnection Connection = new SqlConnection(SecConn))
            {
                Connection.Open();
                string query = "SELECT * FROM Rates";
                using (SqlCommand command = new SqlCommand(query, Connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            rates.Add(new RateVM
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                UsageLevelName = reader["UsageLevelName"].ToString(),
                                UsageLevelNumberStarts = Convert.ToInt32(reader["UsageLevelNumberStarts"]),
                                UsageLevelNumberEnds = Convert.ToInt32(reader["UsageLevelNumberEnds"]),
                                Rate = Convert.ToDecimal(reader["Rate"])

                            });
                        }
                    }
                }
            }

            return rates;
        }

        // Insert Tarrif
        private void InsertTarrif(rateWrapper model)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string Insertquery = "INSERT INTO Rates (UsageLevelName, UsageLevelNumberStarts, UsageLevelNumberEnds, Rate) VALUES"
                                   + "(@UsageLevelName, @UsageLevelNumberStarts, @UsageLevelNumberEnds, @Rate)";

                using (SqlCommand command = new SqlCommand(Insertquery, connection))
                {
                    command.Parameters.AddWithValue("@usageLevelName", model.UsageLevelName);
                    command.Parameters.AddWithValue("@UsageLevelNumberStarts", model.UsageLevelNumberStarts);
                    command.Parameters.AddWithValue("@UsageLevelNumberEnds", model.UsageLevelNumberEnds);
                    command.Parameters.AddWithValue("@Rate", model.Rate);

                    command.ExecuteNonQuery();
                }
            }
        }

        // Update Tarrif Info
        private void UpdateTarrif(rateWrapper model)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string UpdateQuery = "UPDATE Rates SET UsageLevelName = @UsageLevelName, UsageLevelNumberStarts = @UsageLevelNumberStarts, "
                                   + " UsageLevelNumberEnds = @UsageLevelNumberEnds, Rate = @Rate WHERE Id = @Id";

                using (SqlCommand command = new SqlCommand(UpdateQuery, connection))
                {
                    command.Parameters.AddWithValue("@Id", model.Id);
                    command.Parameters.AddWithValue("@UsageLevelName", model.UsageLevelName);
                    command.Parameters.AddWithValue("@UsageLevelNumberStarts", model.UsageLevelNumberStarts);
                    command.Parameters.AddWithValue("@UsageLevelNumberEnds", model.UsageLevelNumberEnds);
                    command.Parameters.AddWithValue("@Rate", model.Rate);

                    command.ExecuteNonQuery();
                };
            }
        }

        // Delete Tarrif
        private void DeleteTarrif(int Id)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string DeleteQuery = "DELETE FROM Rates WHERE Id = @Id";

                using (SqlCommand command = new SqlCommand(DeleteQuery, connection))
                {
                    command.Parameters.AddWithValue("Id", Id);
                    command.ExecuteNonQuery();
                }
            }
        }


        // SPECIAL RATES SECTION STARTS HERE !!! ///

        // Special Rates
        // Rates/SpecialRatesIndex
        public ActionResult SpecialRatesIndex()
        {
            rateWrapper wrapper = new rateWrapper();
            wrapper.rateList = GetSpecialRates();
            return View(wrapper);
        }

        // Update Special Rates
        [HttpPost]
        public JsonResult UpdateSpecialRates(rateWrapper model)
        {
            if (ModelState.IsValid)
            {
                UpdateSpecialTarrif(model);
                return Json(new { success = true, message = "Rate Update Successfully!" });
            }
            return Json(new { success = false, message = "Rate Update Failed. Please Try Again!" });
        }

        // GET: SpecialRates
        private List<RateVM> GetSpecialRates()
        {
            List<RateVM> rates = new List<RateVM>();

            using (SqlConnection Connection = new SqlConnection(SecConn))
            {
                Connection.Open();
                string query = "SELECT * FROM SpecialRates";
                using (SqlCommand command = new SqlCommand(query, Connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            rates.Add(new RateVM
                            {
                                RateID = Convert.ToInt32(reader["RateID"]),
                                SpecialFixedFee = Convert.ToInt32(reader["SpecialFixedFee"]),
                                SpecialRate = Convert.ToDecimal(reader["SpecialRate"]),
                                //Rate = Convert.ToDecimal(reader["Rate"])

                            });
                        }
                    }
                }
            }

            return rates;
        }

        [HttpPost]
        // Update Tarrif Info
        private void UpdateSpecialTarrif(rateWrapper model)
        {
            using (SqlConnection connection = new SqlConnection(SecConn))
            {
                connection.Open();
                string UpdateQuery = "UPDATE SpecialRates SET SpecialFixedFee = @SpecialFixedFee, SpecialRate = @SpecialRate "
                                   + " WHERE RateID = @RateID";

                using (SqlCommand command = new SqlCommand(UpdateQuery, connection))
                {
                    command.Parameters.AddWithValue("@RateID", model.RateID);
                    command.Parameters.AddWithValue("@SpecialFixedFee", model.SpecialFixedFee);
                    command.Parameters.AddWithValue("@SpecialRate", model.SpecialRate);
                    

Views/Rates/Create.cshtml
@model EBS.viewModels.RateVM

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Tarrif | SEC</title>
    <link href="~/Content/Registeration.css" rel="stylesheet" />

</head>
<body>

    @using (Html.BeginForm("Create", "Rates", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <section class="vh-100 gradient-custom;" style="font-family: Verdana, Geneva, Tahoma, sans-serif; ">
            <div class="container py-5 h-100">
                <div class="row justify-content-center align-items-center h-100">

                    <div class="col-12 col-lg-9 col-xl-7">
                        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">

                            <div class="card-body p-4 p-md-5">
                                <h2 class="mb-4 pb-2 pb-md-0 mb-md-5"><strong>Create Tarrif</strong></h2>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="row">
                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(m => m.UsageLevelName)
                                            @Html.EditorFor(model => model.UsageLevelName, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "ulName" } })
                                            @Html.ValidationMessageFor(model => model.UsageLevelName, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.UsageLevelNumber)
                                            @Html.EditorFor(model => model.UsageLevelNumber, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "ulNumber" } })
                                            @Html.ValidationMessageFor(model => model.UsageLevelNumber, "", new { @class = "text-danger" })
                                        </div>

                                    </div>

                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Rate)
                                            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "rate" } })
                                            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                                        </div>

                                    </div>

                                </div>


                                <div class="row">
                                    <div class="col-md-6 mb-4 pb-2">
                                        <button type="submit" value="Create" class="btn btn-success btn-lg btn-block">Create</button>
                                    </div>
                                    <div class="col-md-6 mb-4 pb-2">
                                        @Html.ActionLink("Back", "Index", "Rates", null, new { @class = "btn btn-secondary btn-lg btn-block" })
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    }

    <script>
    // Text validation function
    function validateText(input) {
        if (!isNaN(Number(input.value))) {
            alert('Please enter text');
            input.value = '';
        }
    }

    // Number validation function
    function validateNumber(input) {
        if (isNaN(Number(input.value))) {
            alert('Please enter a number');
            input.value = '';
        }
    }

    // Get elements
    const ulName = document.querySelector('#ulName');
    const ulNumber = document.querySelector('#ulNumber');
    const Rate = document.querySelector('#rate');
   

        // Attach listeners
        ulName.addEventListener('input', () => {
            validateText(ulName);
    });

        ulNumber.addEventListener('input', () => {
            validateNumber(ulNumber);
    });

        Rate.addEventListener('input', () => {
            validateNumber(Rate);
    });

    </script>

</body>
</html>

Views/Rates/Delete.cshtml
@model EBS.viewModels.RateVM

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete Tarrif | SEC</title>
    <link href="~/Content/Registeration.css" rel="stylesheet" />

</head>
<body>

    @using (Html.BeginForm("Delete", "Rates", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <section class="vh-100 gradient-custom;" style="font-family: Verdana, Geneva, Tahoma, sans-serif; ">
            <div class="container py-5 h-100">
                <div class="row justify-content-center align-items-center h-100">

                    <div class="col-12 col-lg-9 col-xl-7">
                        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">

                            <div class="card-body p-4 p-md-5">
                                <h2 class="mb-4 pb-2 pb-md-0 mb-md-5"><strong>Update Tarrif</strong></h2>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                                <div class="row">
                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(m => m.UsageLevelName)
                                            @Html.EditorFor(model => model.UsageLevelName, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "ulName", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.UsageLevelName, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.UsageLevelNumber)
                                            @Html.EditorFor(model => model.UsageLevelNumber, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "ulNumber", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.UsageLevelNumber, "", new { @class = "text-danger" })
                                        </div>

                                    </div>

                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Rate)
                                            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "rate", @disabled = "disabled" } })
                                            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                                        </div>

                                    </div>

                                </div>


                                <div class="row">
                                    <div class="col-md-6 mb-4 pb-2">
                                        <button type="submit" value="Create" class="btn btn-danger btn-lg btn-block">Delete</button>
                                    </div>
                                    <div class="col-md-6 mb-4 pb-2">
                                        @Html.ActionLink("Back", "Index", "Rates", null, new { @class = "btn btn-secondary btn-lg btn-block" })
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    }

    @*<script>
    // Text validation function
    function validateText(input) {
        if (!isNaN(Number(input.value))) {
            alert('Please enter text');
            input.value = '';
        }
    }

    // Number validation function
    function validateNumber(input) {
        if (isNaN(Number(input.value))) {
            alert('Please enter a number');
            input.value = '';
        }
    }

    // Get elements
    const ulName = document.querySelector('#ulName');
    const ulNumber = document.querySelector('#ulNumber');
    const Rate = document.querySelector('#rate');


        // Attach listeners
        ulName.addEventListener('input', () => {
            validateText(ulName);
    });

        ulNumber.addEventListener('input', () => {
            validateNumber(ulNumber);
    });

        Rate.addEventListener('input', () => {
            validateNumber(Rate);
    });

    </script>*@

</body>
</html>

Views/Rates/Edit.cshtml
@model EBS.viewModels.RateVM

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update Tarrif | SEC</title>
    <link href="~/Content/Registeration.css" rel="stylesheet" />

</head>
<body>

    @using (Html.BeginForm("Edit", "Rates", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <section class="vh-100 gradient-custom;" style="font-family: Verdana, Geneva, Tahoma, sans-serif; ">
            <div class="container py-5 h-100">
                <div class="row justify-content-center align-items-center h-100">

                    <div class="col-12 col-lg-9 col-xl-7">
                        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">

                            <div class="card-body p-4 p-md-5">
                                <h2 class="mb-4 pb-2 pb-md-0 mb-md-5"><strong>Update Tarrif</strong></h2>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                                <div class="row">
                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(m => m.UsageLevelName)
                                            @Html.EditorFor(model => model.UsageLevelName, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "ulName" } })
                                            @Html.ValidationMessageFor(model => model.UsageLevelName, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.UsageLevelNumber)
                                            @Html.EditorFor(model => model.UsageLevelNumber, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "ulNumber" } })
                                            @Html.ValidationMessageFor(model => model.UsageLevelNumber, "", new { @class = "text-danger" })
                                        </div>

                                    </div>

                                    <div class="col-md-4 mb-4">

                                        <div class="form-outline form-group">
                                            @Html.LabelFor(model => model.Rate)
                                            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control form-control-lg", @id = "rate" } })
                                            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                                        </div>

                                    </div>

                                </div>


                                <div class="row">
                                    <div class="col-md-6 mb-4 pb-2">
                                        <button type="submit" value="Create" class="btn btn-primary btn-lg btn-block">Update</button>
                                    </div>
                                    <div class="col-md-6 mb-4 pb-2">
                                        @Html.ActionLink("Back", "Index", "Rates", null, new { @class = "btn btn-secondary btn-lg btn-block" })
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    }

    <script>
    // Text validation function
    function validateText(input) {
        if (!isNaN(Number(input.value))) {
            alert('Please enter text');
            input.value = '';
        }
    }

    // Number validation function
    function validateNumber(input) {
        if (isNaN(Number(input.value))) {
            alert('Please enter a number');
            input.value = '';
        }
    }

    // Get elements
    const ulName = document.querySelector('#ulName');
    const ulNumber = document.querySelector('#ulNumber');
    const Rate = document.querySelector('#rate');


        // Attach listeners
        ulName.addEventListener('input', () => {
            validateText(ulName);
    });

        ulNumber.addEventListener('input', () => {
            validateNumber(ulNumber);
    });

        Rate.addEventListener('input', () => {
            validateNumber(Rate);
    });

    </script>

</body>
</html>